### ISSUE TITLE
It fails to build examples on Ubuntu 20.04

### ISSUE THREAD

**Issue by trappedinspacetime** [ferrellsl/Graphapp#1]
First of all, I congratulate you on your project. I needed such examples on Linux. I liked those examples.
I tried to build it via :

           bash ./configure  x11 /usr/lib/x86_64-linux-gnu/
then 

           make
           
It built successfully. 

But when I tried to build the examples I get linking errors such as 

            undefined reference to `png_combine_row'

**Comment by ferrellsl** [comment]
Do not run the configure script if you're using Ubuntu.  Delete your existing directory and download the sources again.  Then, to build the link library just run the make command from within the src folder.  Next, to build one of the examples, just run the make command and add the name of the example you want to build such as the example named alldemo.  I.e. make alldemo or the fastline demo by typing: make fastline

I noticed that the examples folder was in the wrong part of the directory tree so I have moved it to the proper place.  The makefile also had some line feeds that shouldn't have been there as well so I have updated the Linux makefile too.

I just did a clean build on Ubuntu 20 after making the above changes and the library builds as does alldemo and fastline.

**Comment by trappedinspacetime** [comment]
@ferrellsl Awesome examples! Thank you for your help. 
I built them all. I fixed some of the paths, I also had to add `-no-pie` switch to workaround 

        relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
        
error from `Makefile` in the demo directory.

The examples I tried works well except `blend` demo. It keeps crashing though I supply it with the required image files. I know it's hard to manage blending in `X11`.

**Comment by ferrellsl** [comment]
-no-pie is already part of the build.  It's part of the CFLAGS variable in the makefile.

CFLAGS = -DPNG_NO_MMX_CODE -fno-pic -no-pie -O2 -Wall -I. -Ix11 -Iutility -Igui -Ilibz -Ilibpng -Ilibjpeg -Ilibgif -I$(X11_INC_DIR)

The blend exe has to be placed in the demo folder to work properly.

**Comment by trappedinspacetime** [comment]
I debugged it via `strace`.  `blend` demo asks `unifont` to be either in `~/graphappfonts/unicode/16.txt` or  `/graphappfonts/unifont/16.txt`
I copied the `unicode` directory in `Graphapp/fonts/unicode`  into  `~/graphappfonts/`, it fixed the crash.

> -no-pie is already part of the build. It's part of the CFLAGS variable in the makefile.

Yes it exists in `src/Makefile` but it doesn't exist in `src/demo/Makefile`.

Thank you for all your help.
Best regards.
